# Required by readthedocs
version: 2

# Set the OS, Python version etc.
build:
  os: ubuntu-22.04
  tools:
    python: miniconda3-4.7

# Declare Python requirements
conda:
  environment: environment-min.yml

# Build documentation using the configuration file below
sphinx:
  configuration: docs/source/conf.py